### PR TITLE
Fix library name & install rule

### PR DESCRIPTION
**Pull request by jschueller**
It should be renamed hdpf for consistency
https://packages.debian.org/bullseye/amd64/libhpdf-dev/filelist

### CODE REVIEW

**Comment by bramton** [comment]
Thanks! What silly of me to get the library name wrong 😮

**Comment by jschueller** [comment]
why did it change then ?

**Comment by jschueller** [comment]
@bramton you closed the issue but the commit did not land in the repo, what happened ?

**Comment by bramton** [comment]
Ah, the changes have been pushed to the `devel` branch.

**Comment by jschueller** [comment]
I dont see it:
https://github.com/libharu/libharu/tree/devel

**Comment by bramton** [comment]
Indeed, you're right, the changes are not present in the devel branch. I will look into this.

**Comment by bramton** [comment]
.... and it's fixed! bc2fdfa1369bb9f10ee486ae7147fbc9cd9f4e69

**Pull request closed without merging**
