### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by FrankXie05**
`libharu` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `libharu` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `libharu`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/libharu/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

### CODE REVIEW

**Comment by bramton** [comment]
Thank you!

**Comment by FrankXie05** [comment]
@bramton Thanks for your response, why closed this PR ?

**Comment by bramton** [comment]
My bad, I thought I had merged the PR to the devel branch. Instead GitHub (or I) did something wrong and nothing got committed. The changes are now present in the devel branch.

**Comment by FrankXie05** [comment]
@bramton We should reopen it. :)

**Comment by bramton** [comment]
With some git based trickery I managed to get changes and commit (20a9370d106d69d9c33af396282390d8b7e10002) them.

**Pull request closed without merging**
